cmake_minimum_required(VERSION 3.10)
project(Benchmark)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0")
include_directories(include)
file(GLOB SOURCES "src/*.cpp")
list(APPEND SOURCES src/kmeans.c src/pgm.c main.cpp)
find_package(benchmark REQUIRED)
add_executable(Benchmark ${SOURCES})
target_link_libraries(Benchmark benchmark::benchmark m)
